### ISSUE TITLE
No data fetch

### ISSUE THREAD

**Issue by jayantanth** [Dineshkarthik/wiki-user-contributions#1]
Hi, there is no data fetch from this tool

![Screenshot Capture - 2021-01-13 - 00-30-26](https://user-images.githubusercontent.com/1370149/104360094-8c937100-5536-11eb-9525-4f82ca37ac0d.png)

**Comment by Dineshkarthik** [comment]
Hi, @jayantanth  the user name is case-sensitive and from a quick try  in `en.wikipedia.org/wiki/User:/` found that your user name is `Jayantanth` and it fetches result.

**Comment by jayantanth** [comment]
Thanks for your prompt reply. Its was my mistake, giving wrong user name.
